const fs = require('fs');

const dbPath = 'program-db/database/practice-db.json';
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

db.practices = db.practices.filter((item) => item.chapterCode !== 'e5-2-7');
db.bindings = db.bindings.filter((item) => !(item.targetType === 'chapter' && item.targetId === 'e5-2-7'));

const base = {
  enabled: true,
  mode: 'generator',
  questionCount: 5,
  stage: '國小',
  grade: '小五',
  term: '下學期',
  chapter: '表面積',
  domain: '空間與形狀',
  prompt: '',
  answer: '',
  examples: [],
  notes: [],
};

const practices = [
  {
    id: 'practice-e5-2-7-cube-edge-surface-drill',
    title: '正方體表面積（已知邊長）',
    generatorKey: 'e5-2-7-cube-edge-surface-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '正方體', '邊長'],
    usage: ['先建立正方體有 6 個全等面的概念，再練習邊長平方後乘 6。'],
    tips: ['先算一個面的面積，再乘 6，比較不容易漏面。'],
    mistakes: ['把表面積誤算成邊長乘 6，忘了面積要先平方。'],
  },
  {
    id: 'practice-e5-2-7-cube-face-area-surface-drill',
    title: '正方體表面積（已知一面面積）',
    generatorKey: 'e5-2-7-cube-face-area-surface-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '正方體', '一面面積'],
    usage: ['當學生已經知道一個面的面積時，直接連到 6 個面的總面積。'],
    tips: ['抓住 6 個面的面積都相等，直接用單面積乘 6。'],
    mistakes: ['把單一面的面積當成整體表面積。'],
  },
  {
    id: 'practice-e5-2-7-cube-inverse-edge-drill',
    title: '已知表面積求邊長',
    generatorKey: 'e5-2-7-cube-inverse-edge-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '正方體', '逆向'],
    usage: ['訓練學生先用總表面積除以 6，再從單面積找回邊長。'],
    tips: ['先除以 6 求一個面的面積，再想哪個平方等於這個數。'],
    mistakes: ['直接拿表面積開根號，忘了先除以 6。'],
  },
  {
    id: 'practice-e5-2-7-rect-surface-drill',
    title: '長方體表面積（三邊不同）',
    generatorKey: 'e5-2-7-rect-surface-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '長方體'],
    usage: ['建立長方體表面積公式 2×(長寬+寬高+長高) 的基本運用。'],
    tips: ['先把三組不同的面列出來，再乘 2。'],
    mistakes: ['少算一組面，或把 2 只乘到最後一項。'],
  },
  {
    id: 'practice-e5-2-7-special-rect-surface-drill',
    title: '特殊長方體表面積（兩面正方形）',
    generatorKey: 'e5-2-7-special-rect-surface-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '長方體', '兩面正方形'],
    usage: ['用特殊結構簡化計算，幫助學生看出 2 個正方形面與 4 個相同長方形面。'],
    tips: ['先分成 2 個正方形面和 4 個長方形面。'],
    mistakes: ['把 4 個側面誤算成只有 2 個。'],
  },
  {
    id: 'practice-e5-2-7-volume-to-surface-drill',
    title: '透過體積求表面積',
    generatorKey: 'e5-2-7-volume-to-surface-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '體積', '逆向'],
    usage: ['先由體積和已知邊長求出缺少的一邊，再回頭計算表面積。'],
    tips: ['先完成 体積÷已知兩邊 = 未知邊，再套表面積公式。'],
    mistakes: ['直接拿體積當表面積的一部分使用。'],
  },
  {
    id: 'practice-e5-2-7-full-cover-application-drill',
    title: '生活情境全表面積',
    generatorKey: 'e5-2-7-full-cover-application-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '包裝', '塗漆'],
    usage: ['把表面積放回塗漆、彩繪、包裝等完整外表面的情境。'],
    tips: ['先判斷題目是不是要算全部外表面。'],
    mistakes: ['把只包側面和包全部外表面混在一起。'],
  },
  {
    id: 'practice-e5-2-7-lateral-wrap-drill',
    title: '側面一圈包裝面積',
    generatorKey: 'e5-2-7-lateral-wrap-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '側面', '包裝'],
    usage: ['專練只貼側面一圈的題型，建立側面積 = 底面周長 × 高。'],
    tips: ['看到「繞一圈」先想側面，不含上面和下面。'],
    mistakes: ['把上下面也一起算進去。'],
  },
  {
    id: 'practice-e5-2-7-cut-increase-drill',
    title: '切割後表面積增加',
    generatorKey: 'e5-2-7-cut-increase-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '切割', '增加'],
    usage: ['觀察每切一刀會多出 2 個切面，訓練空間感。'],
    tips: ['先求每個切面的面積，再乘刀數和 2。'],
    mistakes: ['只加一個切面，忘了前後各多 1 個。'],
  },
  {
    id: 'practice-e5-2-7-merge-decrease-drill',
    title: '黏合後表面積減少',
    generatorKey: 'e5-2-7-merge-decrease-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '黏合', '減少'],
    usage: ['觀察兩塊立體貼合後，接觸面會消失 2 個面積。'],
    tips: ['每黏住 1 次，就少 2 個接觸面的面積。'],
    mistakes: ['只減 1 個面，或忘了有幾個接觸處。'],
  },
  {
    id: 'practice-e5-2-7-unit-cube-surface-drill',
    title: '積木排成長方體的表面積',
    generatorKey: 'e5-2-7-unit-cube-surface-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '積木', '長方體'],
    usage: ['把單位積木排法轉成長方體外形，再算表面積。'],
    tips: ['先看排成幾乘幾乘幾，再用長方體表面積公式。'],
    mistakes: ['只看積木總數，沒有先辨認外形尺寸。'],
  },
  {
    id: 'practice-e5-2-7-arrangement-compare-drill',
    title: '不同排列的表面積比較',
    generatorKey: 'e5-2-7-arrangement-compare-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-7', '表面積', '排列比較', '積木'],
    usage: ['比較同樣數量積木在不同排法下的表面積大小。'],
    tips: ['先各自算表面積，再比較；通常越扁長表面積越大。'],
    mistakes: ['看到積木數相同，就以為表面積也相同。'],
  },
  {
    id: 'practice-e5-2-7-cube-three-subtypes',
    title: '正方體三小類綜合',
    generatorKey: 'e5-2-7-cube-three-subtypes',
    difficulty: 'easy',
    subtypeCount: 3,
    relatedPracticeIds: [
      'practice-e5-2-7-cube-edge-surface-drill',
      'practice-e5-2-7-cube-face-area-surface-drill',
      'practice-e5-2-7-cube-inverse-edge-drill',
    ],
    tags: ['e5-2-7', '表面積', '正方體', '三小類綜合'],
    usage: ['把正方體表面積的順向、單面反推、總表面積反推放在同一組。'],
    tips: ['先分清楚題目給的是邊長、單面積，還是總表面積。'],
    mistakes: ['逆向題沒有先把題目轉回單一面的資訊。'],
  },
  {
    id: 'practice-e5-2-7-rect-three-subtypes',
    title: '長方體三小類綜合',
    generatorKey: 'e5-2-7-rect-three-subtypes',
    difficulty: 'medium',
    subtypeCount: 3,
    relatedPracticeIds: [
      'practice-e5-2-7-rect-surface-drill',
      'practice-e5-2-7-special-rect-surface-drill',
      'practice-e5-2-7-volume-to-surface-drill',
    ],
    tags: ['e5-2-7', '表面積', '長方體', '三小類綜合'],
    usage: ['整理長方體表面積、特殊結構簡化與透過體積反推。'],
    tips: ['先補齊缺少的邊，再統一回到表面積公式。'],
    mistakes: ['把不同題型混成只套一條公式，不先判斷條件。'],
  },
  {
    id: 'practice-e5-2-7-life-two-subtypes',
    title: '生活情境兩小類綜合',
    generatorKey: 'e5-2-7-life-two-subtypes',
    difficulty: 'easy',
    subtypeCount: 2,
    relatedPracticeIds: [
      'practice-e5-2-7-full-cover-application-drill',
      'practice-e5-2-7-lateral-wrap-drill',
    ],
    tags: ['e5-2-7', '表面積', '生活情境'],
    usage: ['練習從語句判斷是全部外表面還是只算側面。'],
    tips: ['關鍵詞像「全部外面」與「繞一圈」要先辨認。'],
    mistakes: ['沒有判斷題意就直接代公式。'],
  },
  {
    id: 'practice-e5-2-7-cut-merge-two-subtypes',
    title: '切割與合併兩小類綜合',
    generatorKey: 'e5-2-7-cut-merge-two-subtypes',
    difficulty: 'medium',
    subtypeCount: 2,
    relatedPracticeIds: [
      'practice-e5-2-7-cut-increase-drill',
      'practice-e5-2-7-merge-decrease-drill',
    ],
    tags: ['e5-2-7', '表面積', '切割', '合併'],
    usage: ['對照練習切割會增加、黏合會減少表面積的核心觀念。'],
    tips: ['切割看新增的面，黏合看消失的面。'],
    mistakes: ['把增加和減少的方向弄反。'],
  },
  {
    id: 'practice-e5-2-7-block-compare-two-subtypes',
    title: '積木與排列兩小類綜合',
    generatorKey: 'e5-2-7-block-compare-two-subtypes',
    difficulty: 'medium',
    subtypeCount: 2,
    relatedPracticeIds: [
      'practice-e5-2-7-unit-cube-surface-drill',
      'practice-e5-2-7-arrangement-compare-drill',
    ],
    tags: ['e5-2-7', '表面積', '積木', '排列'],
    usage: ['把積木排法與不同排列比較放在同一組，補足空間感。'],
    tips: ['先看外形尺寸，再想表面積，不要只看積木個數。'],
    mistakes: ['以為同樣顆數的積木表面積一定相同。'],
  },
].map((item) => ({ ...base, ...item, chapterCode: 'e5-2-7' }));

db.practices.push(...practices);

db.bindings.push(
  {
    practiceId: 'practice-e5-2-7-cube-three-subtypes',
    targetType: 'chapter',
    targetId: 'e5-2-7',
    enabled: true,
    order: 1,
  },
  {
    practiceId: 'practice-e5-2-7-rect-three-subtypes',
    targetType: 'chapter',
    targetId: 'e5-2-7',
    enabled: true,
    order: 2,
  },
  {
    practiceId: 'practice-e5-2-7-life-two-subtypes',
    targetType: 'chapter',
    targetId: 'e5-2-7',
    enabled: true,
    order: 3,
  },
  {
    practiceId: 'practice-e5-2-7-cut-merge-two-subtypes',
    targetType: 'chapter',
    targetId: 'e5-2-7',
    enabled: true,
    order: 4,
  },
  {
    practiceId: 'practice-e5-2-7-block-compare-two-subtypes',
    targetType: 'chapter',
    targetId: 'e5-2-7',
    enabled: true,
    order: 5,
  },
);

db.meta = db.meta || {};
db.meta.practiceCount = db.practices.length;
db.meta.bindingCount = db.bindings.length;
db.meta.updatedAt = new Date().toISOString();

fs.writeFileSync(dbPath, `${JSON.stringify(db, null, 2)}\n`, 'utf8');
console.log('Updated e5-2-7 practices:', practices.length);
