const fs = require('fs');
const path = require('path');

const dbPath = path.join(__dirname, 'program-db', 'database', 'practice-db.json');
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

const practiceIds = [
  'practice-e5-2-1-basic-volume-drill',
  'practice-e5-2-1-reverse-volume-drill',
  'practice-e5-2-1-volume-unit-convert-drill',
  'practice-e5-2-1-capacity-convert-drill',
  'practice-e5-2-1-mixed-unit-volume-drill',
  'practice-e5-2-1-cutting-composite-drill',
  'practice-e5-2-1-fill-cut-drill',
  'practice-e5-2-1-water-displacement-drill',
  'practice-e5-2-1-thickness-capacity-drill',
  'practice-e5-2-1-large-container-drill',
  'practice-e5-2-1-basic-two-subtypes',
  'practice-e5-2-1-convert-three-subtypes',
  'practice-e5-2-1-composite-three-subtypes',
  'practice-e5-2-1-applied-two-subtypes',
];

db.practices = db.practices.filter((item) => !practiceIds.includes(item.id));
db.bindings = db.bindings.filter((item) => !(item.targetType === 'chapter' && item.targetId === 'e5-2-1'));

function makePractice({
  id,
  title,
  generatorKey,
  difficulty,
  questionCount,
  subtypeCount = 1,
  relatedPracticeIds = [],
  tags = [],
  usage = [],
  tips = [],
  mistakes = [],
}) {
  return {
    id,
    enabled: true,
    mode: 'generator',
    title,
    generatorKey,
    difficulty,
    questionCount,
    subtypeCount,
    relatedPracticeIds,
    chapterCode: 'e5-2-1',
    stage: '國小',
    grade: '小五',
    term: '下學期',
    chapter: '體積',
    domain: '數與量',
    prompt: '',
    answer: '',
    tags: ['e5-2-1', '體積', ...tags],
    usage,
    examples: [],
    tips,
    notes: [],
    mistakes,
  };
}

const newPractices = [
  makePractice({
    id: 'practice-e5-2-1-basic-volume-drill',
    title: '基本長方體與正方體體積',
    generatorKey: 'e5-2-1-basic-volume-drill',
    difficulty: 'easy',
    questionCount: 5,
    tags: ['基本體積'],
    usage: ['練習長方體與正方體的體積公式。'],
    tips: ['先分清楚是長方體還是正方體，再套公式。'],
    mistakes: ['長、寬、高少乘一個。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-reverse-volume-drill',
    title: '逆向求未知邊長或高',
    generatorKey: 'e5-2-1-reverse-volume-drill',
    difficulty: 'easy',
    questionCount: 5,
    tags: ['逆向'],
    usage: ['已知體積後，反求高、邊長或另一個邊。'],
    tips: ['先把體積公式寫出來，再用除法反推。'],
    mistakes: ['體積反推時忘了要連續除以兩個邊長。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-volume-unit-convert-drill',
    title: '體積單位換算',
    generatorKey: 'e5-2-1-volume-unit-convert-drill',
    difficulty: 'easy',
    questionCount: 5,
    tags: ['單位換算'],
    usage: ['練習立方公尺與立方公分的換算。'],
    tips: ['記住 1 立方公尺 = 1,000,000 立方公分。'],
    mistakes: ['把長度換算 100 倍誤當成立方換算。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-capacity-convert-drill',
    title: '體積、容量與水度換算',
    generatorKey: 'e5-2-1-capacity-convert-drill',
    difficulty: 'easy',
    questionCount: 5,
    tags: ['容量換算'],
    usage: ['練習立方公尺、公升與度水的轉換。'],
    tips: ['記住 1 立方公尺 = 1000 公升 = 1 度水。'],
    mistakes: ['把公升和立方公尺的倍數搞反。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-mixed-unit-volume-drill',
    title: '跨單位混合體積',
    generatorKey: 'e5-2-1-mixed-unit-volume-drill',
    difficulty: 'medium',
    questionCount: 5,
    tags: ['跨單位'],
    usage: ['先統一長、寬、高單位，再計算體積。'],
    tips: ['全部換成同一單位後再乘。'],
    mistakes: ['沒有先統一單位就直接相乘。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-cutting-composite-drill',
    title: '切割法複合體積',
    generatorKey: 'e5-2-1-cutting-composite-drill',
    difficulty: 'medium',
    questionCount: 5,
    tags: ['複合體積', '切割法'],
    usage: ['把複合形體拆成兩個長方體相加。'],
    tips: ['先決定切成哪兩塊最容易算。'],
    mistakes: ['拆開後漏算其中一塊。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-fill-cut-drill',
    title: '填補法缺口體積',
    generatorKey: 'e5-2-1-fill-cut-drill',
    difficulty: 'medium',
    questionCount: 5,
    tags: ['複合體積', '填補法'],
    usage: ['先補成大長方體，再扣掉缺口。'],
    tips: ['先算完整體積，再算挖掉的部分。'],
    mistakes: ['只算外框，忘了扣缺口。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-water-displacement-drill',
    title: '水位上升與排水體積',
    generatorKey: 'e5-2-1-water-displacement-drill',
    difficulty: 'medium',
    questionCount: 5,
    tags: ['排水體積'],
    usage: ['利用底面積 × 水位變化求排開體積。'],
    tips: ['先找底面積，再乘水位上升高度。'],
    mistakes: ['把容器高度誤當成水位變化。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-thickness-capacity-drill',
    title: '容積與厚度計算',
    generatorKey: 'e5-2-1-thickness-capacity-drill',
    difficulty: 'medium',
    questionCount: 5,
    tags: ['容積', '厚度'],
    usage: ['區分外部尺寸與內部尺寸，先扣厚度再算容積。'],
    tips: ['長和寬通常各扣 2 次厚度，高要看有沒有蓋。'],
    mistakes: ['高度多扣或少扣一次厚度。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-large-container-drill',
    title: '大型容器生活應用',
    generatorKey: 'e5-2-1-large-container-drill',
    difficulty: 'medium',
    questionCount: 5,
    tags: ['生活應用'],
    usage: ['把泳池、水箱、水費度數連到體積與容量。'],
    tips: ['先算立方公尺，再視題意換成公升。'],
    mistakes: ['忘記最後還要換成公升或度水。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-basic-two-subtypes',
    title: '基本體積與逆向二小類綜合',
    generatorKey: 'e5-2-1-basic-two-subtypes',
    difficulty: 'easy',
    questionCount: 5,
    subtypeCount: 2,
    relatedPracticeIds: [
      'practice-e5-2-1-basic-volume-drill',
      'practice-e5-2-1-reverse-volume-drill',
    ],
    tags: ['基礎綜合'],
    usage: ['統整基本體積與逆向反求。'],
    tips: ['先判斷題目是正算還是反算。'],
    mistakes: ['正算與反算公式混在一起。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-convert-three-subtypes',
    title: '單位、容積與換算三小類綜合',
    generatorKey: 'e5-2-1-convert-three-subtypes',
    difficulty: 'easy',
    questionCount: 5,
    subtypeCount: 3,
    relatedPracticeIds: [
      'practice-e5-2-1-volume-unit-convert-drill',
      'practice-e5-2-1-capacity-convert-drill',
      'practice-e5-2-1-mixed-unit-volume-drill',
    ],
    tags: ['換算綜合'],
    usage: ['統整體積單位、容量與跨單位計算。'],
    tips: ['先統一單位，最後再看要不要換答案單位。'],
    mistakes: ['把立方與長度單位換算混在一起。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-composite-three-subtypes',
    title: '複合體積與排水三小類綜合',
    generatorKey: 'e5-2-1-composite-three-subtypes',
    difficulty: 'medium',
    questionCount: 5,
    subtypeCount: 3,
    relatedPracticeIds: [
      'practice-e5-2-1-cutting-composite-drill',
      'practice-e5-2-1-fill-cut-drill',
      'practice-e5-2-1-water-displacement-drill',
    ],
    tags: ['複合綜合'],
    usage: ['統整拆解、填補與排水三種體積思路。'],
    tips: ['先判斷這題是相加、相減，還是水位變化。'],
    mistakes: ['題型判斷錯，導致用錯運算。'],
  }),
  makePractice({
    id: 'practice-e5-2-1-applied-two-subtypes',
    title: '容積與生活應用二小類綜合',
    generatorKey: 'e5-2-1-applied-two-subtypes',
    difficulty: 'medium',
    questionCount: 5,
    subtypeCount: 2,
    relatedPracticeIds: [
      'practice-e5-2-1-thickness-capacity-drill',
      'practice-e5-2-1-large-container-drill',
    ],
    tags: ['應用綜合'],
    usage: ['統整容器厚度與大型容器的生活應用。'],
    tips: ['先分清楚外尺寸、內尺寸與答案單位。'],
    mistakes: ['容積與外部體積混淆。'],
  }),
];

db.practices.push(...newPractices);

db.bindings.push(
  { practiceId: 'practice-e5-2-1-basic-two-subtypes', targetType: 'chapter', targetId: 'e5-2-1', enabled: true, order: 1 },
  { practiceId: 'practice-e5-2-1-convert-three-subtypes', targetType: 'chapter', targetId: 'e5-2-1', enabled: true, order: 2 },
  { practiceId: 'practice-e5-2-1-composite-three-subtypes', targetType: 'chapter', targetId: 'e5-2-1', enabled: true, order: 3 },
  { practiceId: 'practice-e5-2-1-applied-two-subtypes', targetType: 'chapter', targetId: 'e5-2-1', enabled: true, order: 4 },
);

fs.writeFileSync(dbPath, `${JSON.stringify(db, null, 2)}\n`, 'utf8');
console.log(`updated ${newPractices.length} practices for e5-2-1`);
