const fs = require('fs');

const dbPath = 'program-db/database/practice-db.json';
const db = JSON.parse(fs.readFileSync(dbPath, 'utf8'));

db.practices = db.practices.filter((item) => item.chapterCode !== 'e5-2-6');
db.bindings = db.bindings.filter((item) => !(item.targetType === 'chapter' && item.targetId === 'e5-2-6'));

const base = {
  enabled: true,
  mode: 'generator',
  questionCount: 5,
  stage: '國小',
  grade: '小五',
  term: '下學期',
  chapter: '整數、小數除以整數',
  domain: '數與量',
  prompt: '',
  answer: '',
  examples: [],
  notes: [],
};

const practices = [
  {
    id: 'practice-e5-2-6-integer-divide-decimal-drill',
    title: '整數除以整數（商是小數）',
    generatorKey: 'e5-2-6-integer-divide-decimal-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '整數除以整數', '商是小數', '直式計算'],
    usage: ['當整數除法不能整除時，練習在個位後補小數點與 0 繼續除。'],
    tips: ['先做整數部分；不夠除時，在被除數後補 0，商也要點上小數點。'],
    mistakes: ['常忘記在商的整數部分後點小數點，或補 0 後對位錯誤。'],
  },
  {
    id: 'practice-e5-2-6-decimal-divide-integer-drill',
    title: '小數除以整數（精確除盡）',
    generatorKey: 'e5-2-6-decimal-divide-integer-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '小數除以整數', '精確除盡'],
    usage: ['練習商的小數點與被除數的小數點對齊的基本直式。'],
    tips: ['被除數有小數點時，商的小數點要對齊。'],
    mistakes: ['商的小數點常放錯位置，或把小數當整數直接除。'],
  },
  {
    id: 'practice-e5-2-6-quotient-zero-gap-drill',
    title: '商缺位與補 0',
    generatorKey: 'e5-2-6-quotient-zero-gap-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '商缺位', '補0', '位值'],
    usage: ['用來練習某一位不夠除時，商要補 0 佔位的情況。'],
    tips: ['如果某一位不夠除，就先在商寫 0，再帶下一位。'],
    mistakes: ['最常漏寫商的 0，導致整個答案位值錯掉。'],
  },
  {
    id: 'practice-e5-2-6-fraction-to-decimal-drill',
    title: '分數化為小數',
    generatorKey: 'e5-2-6-fraction-to-decimal-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '分數化小數', '帶分數'],
    usage: ['把分數看成除法，建立 a ÷ b 與 a/b 的連結。'],
    tips: ['真分數、假分數、帶分數都可改寫成除法再算。'],
    mistakes: ['常把帶分數只算分數部分，忘記整數部分要一起保留。'],
  },
  {
    id: 'practice-e5-2-6-divide-by-powers-drill',
    title: '除以 10、100、1000',
    generatorKey: 'e5-2-6-divide-by-powers-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '位移', '除以10', '除以100', '除以1000'],
    usage: ['用來建立除以 10、100、1000 的位值移動規律。'],
    tips: ['除數有幾個 0，小數點就往左移幾位。'],
    mistakes: ['常把方向看反，寫成往右移。'],
  },
  {
    id: 'practice-e5-2-6-quotient-rounding-drill',
    title: '除不盡時取概數',
    generatorKey: 'e5-2-6-quotient-rounding-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '概數', '四捨五入', '除不盡'],
    usage: ['用在小數除法不能整除時，練習取到指定位數。'],
    tips: ['要取到第幾位，就先多算一位再判斷是否進位。'],
    mistakes: ['常直接截斷，不做四捨五入。'],
  },
  {
    id: 'practice-e5-2-6-equal-sharing-drill',
    title: '平分分配問題',
    generatorKey: 'e5-2-6-equal-sharing-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '平分', '平均分配', '應用題'],
    usage: ['總量固定、平均分成若干份時使用。'],
    tips: ['先找總量，再除以份數。'],
    mistakes: ['有些學生會反過來用乘法，或漏掉單位。'],
  },
  {
    id: 'practice-e5-2-6-geometry-dimension-drill',
    title: '幾何量與長寬反推',
    generatorKey: 'e5-2-6-geometry-dimension-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '面積反推', '周長反推', '幾何應用'],
    usage: ['已知面積、周長或總長，反推每邊長或每段長。'],
    tips: ['先寫出關係式，例如 寬 = 面積 ÷ 長、邊長 = 周長 ÷ 4。'],
    mistakes: ['常忘記正方形有 4 條邊，或把平方單位與長度單位混在一起。'],
  },
  {
    id: 'practice-e5-2-6-average-unit-drill',
    title: '平均單位量計算',
    generatorKey: 'e5-2-6-average-unit-drill',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '平均', '單位量', '單價'],
    usage: ['求每盒、每杯、每小時、每件是多少時使用。'],
    tips: ['先確認總量和總份數，再除出 1 單位的量。'],
    mistakes: ['常把總量與總份數顛倒。'],
  },
  {
    id: 'practice-e5-2-6-time-unit-convert-drill',
    title: '時間單位換算',
    generatorKey: 'e5-2-6-time-unit-convert-drill',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [],
    tags: ['e5-2-6', '時間換算', '分鐘換小時', '小時換日'],
    usage: ['把分、時、日之間用除法換成小數表示。'],
    tips: ['分換時除以 60；時換日除以 24。'],
    mistakes: ['常把 60 和 24 用錯，或答案單位忘記改。'],
  },
  {
    id: 'practice-e5-2-6-basic-three-subtypes',
    title: '直式計算三小類綜合',
    generatorKey: 'e5-2-6-basic-three-subtypes',
    difficulty: 'easy',
    subtypeCount: 3,
    relatedPracticeIds: [
      'practice-e5-2-6-integer-divide-decimal-drill',
      'practice-e5-2-6-decimal-divide-integer-drill',
      'practice-e5-2-6-quotient-zero-gap-drill',
    ],
    tags: ['e5-2-6', '三小類綜合', '直式計算'],
    usage: ['把本章最核心的三種直式除法放在同一組反覆練習。'],
    tips: ['先看是不是要補 0，再看商的小數點要落在哪裡。'],
    mistakes: ['把不同類型混在一起時，最容易錯在位值與補 0。'],
  },
  {
    id: 'practice-e5-2-6-convert-two-subtypes',
    title: '轉換兩小類綜合',
    generatorKey: 'e5-2-6-convert-two-subtypes',
    difficulty: 'easy',
    subtypeCount: 2,
    relatedPracticeIds: [
      'practice-e5-2-6-fraction-to-decimal-drill',
      'practice-e5-2-6-divide-by-powers-drill',
    ],
    tags: ['e5-2-6', '兩小類綜合', '換算'],
    usage: ['把除法與位值、分數之間的轉換一起練。'],
    tips: ['遇到分數先想除法；遇到 10、100、1000 先想位移。'],
    mistakes: ['常把規律題硬算，反而更容易出錯。'],
  },
  {
    id: 'practice-e5-2-6-rounding-one-subtype',
    title: '概數處理',
    generatorKey: 'e5-2-6-rounding-one-subtype',
    difficulty: 'medium',
    subtypeCount: 1,
    relatedPracticeIds: [
      'practice-e5-2-6-quotient-rounding-drill',
    ],
    tags: ['e5-2-6', '概數'],
    usage: ['專門練習除不盡時的取概數。'],
    tips: ['算到指定位的下一位，才能正確四捨五入。'],
    mistakes: ['直接停在指定位置，不看下一位。'],
  },
  {
    id: 'practice-e5-2-6-application-three-subtypes',
    title: '應用三小類綜合',
    generatorKey: 'e5-2-6-application-three-subtypes',
    difficulty: 'medium',
    subtypeCount: 3,
    relatedPracticeIds: [
      'practice-e5-2-6-equal-sharing-drill',
      'practice-e5-2-6-geometry-dimension-drill',
      'practice-e5-2-6-average-unit-drill',
    ],
    tags: ['e5-2-6', '三小類綜合', '應用題'],
    usage: ['把平分、幾何反推、平均單位量放在同章節綜合練。'],
    tips: ['先判斷題目在問「每一份」還是「某一邊」或「每 1 單位」。'],
    mistakes: ['學生常看不出除法關係，容易誤用乘法。'],
  },
  {
    id: 'practice-e5-2-6-time-one-subtype',
    title: '時間換算應用',
    generatorKey: 'e5-2-6-time-one-subtype',
    difficulty: 'easy',
    subtypeCount: 1,
    relatedPracticeIds: [
      'practice-e5-2-6-time-unit-convert-drill',
    ],
    tags: ['e5-2-6', '時間換算'],
    usage: ['用在分、時、日之間的除法換算。'],
    tips: ['確認是大單位換小單位還是小單位換大單位。'],
    mistakes: ['把 60 與 24 背成規則但沒看單位，容易套錯。'],
  },
].map((item) => ({ ...base, ...item, chapterCode: 'e5-2-6' }));

db.practices.push(...practices);

db.bindings.push(
  {
    practiceId: 'practice-e5-2-6-basic-three-subtypes',
    targetType: 'chapter',
    targetId: 'e5-2-6',
    enabled: true,
    order: 1,
  },
  {
    practiceId: 'practice-e5-2-6-convert-two-subtypes',
    targetType: 'chapter',
    targetId: 'e5-2-6',
    enabled: true,
    order: 2,
  },
  {
    practiceId: 'practice-e5-2-6-rounding-one-subtype',
    targetType: 'chapter',
    targetId: 'e5-2-6',
    enabled: true,
    order: 3,
  },
  {
    practiceId: 'practice-e5-2-6-application-three-subtypes',
    targetType: 'chapter',
    targetId: 'e5-2-6',
    enabled: true,
    order: 4,
  },
  {
    practiceId: 'practice-e5-2-6-time-one-subtype',
    targetType: 'chapter',
    targetId: 'e5-2-6',
    enabled: true,
    order: 5,
  },
);

db.meta.practiceCount = db.practices.length;
db.meta.bindingCount = db.bindings.length;
db.meta.updatedAt = new Date().toISOString();

fs.writeFileSync(dbPath, JSON.stringify(db, null, 2) + '\n');
console.log(`Updated e5-2-6 practices: ${practices.length}`);
